# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Duality of technology
description: seo-faper's blog
repository: https://github.com/Seo-Faper/seo-faper.github.io
baseurl: / # the subpath of your site, e.g. /blog
url: https://seo-faper.github.io # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: seo-faper
email: dswhdcks@naver.com

navigation:
  - text: Home
    url: /
  - text: 삶에 도움 되는 것들
    url: /cheatsheet
  - text: 전체 글 보기
    url: /posts
  - text: 프로젝트
    url: /projects
  - text: 알고리즘
    url: /algorithm
  - text: 정보보안
    url: /infosec
  - text: 기타 둥둥
    url: /etc

projects:
  - name: league of legend DST
    description: 돈스타브 투게더 모드
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

  - name: Project, 벌레캠프!
    description: Ren'py를 이용한 PS 버추얼 노벨
    link: https://sobolevn.github.io/git-secret
    image: https://raw.githubusercontent.com/Seo-Faper/seo-faper.github.io/main/img/renpy/girl1.png

  - name: Nonogram for React
    description: 네모네모로직을 플레이 할 수 있는 웹페이지
    link: https://github.com/Seo-Faper/Toy_Project_Nonogram
    image: https://raw.githubusercontent.com/Seo-Faper/cq_assets/master/heroes/cos_ar_7_15.png

social:
  - service: github
    username: seo-faper
    link: https://github.com/seo-faper

# Plugins
gems:
  - jekyll-seo-tag
future: true
