# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 쫑이 하우스
description: seo-faper's blog
repository: https://github.com/Seo-Faper/
baseurl: / # the subpath of your site, e.g. /blog
url: https://seo-faper.github.io # the base hostname & protocol for your site

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  math_engine: mathjax
# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: seo-faper
email: dswhdcks@naver.com

navigation:
  - text: Home
    url: /
  - text: 삶에 도움 되는 것들
    url: /cheatsheet
  - text: 전체 글 보기
    url: /posts
  - text: 프로젝트
    url: /projects
  - text: 알고리즘
    url: /algorithm
  - text: 정보보안
    url: /infosec
  - text: 기타 둥둥
    url: /etc

projects:
  - name: Project, 벌레캠프!
    description: Ren'py를 이용한 PS 비주얼 노벨
    link: https://github.com/Seo-Faper/Project_Berlekamp
    image: https://raw.githubusercontent.com/Seo-Faper/seo-faper.github.io/main/img/renpy/girl2.png

  - name: Get Your Hash
    description: 해쉬값을 알아내는 사이트 
    link: https://seo-faper.github.io/HashBr0wn/
    image: https://raw.githubusercontent.com/Seo-Faper/HashBr0wn/main/hash/public/favicon.ico

  # - name: 크크 위키 (작성중)
  #   description: 크루세이더 퀘스트 용사 등급표를 볼 수 있는 사이트
  #   link: https://github.com/Seo-Faper/Portfolio
  #   image: https://raw.githubusercontent.com/Seo-Faper/cq_assets/master/common/giftbox.png

social:
  - service: github
    username: seo-faper
    link: https://github.com/seo-faper

# Plugins
gems:
  - jekyll-seo-tag
future: true
